var annotated_dup =
[
    [ "_report_t", "struct__report__t.html", "struct__report__t" ],
    [ "_target_info_t", "struct__target__info__t.html", "struct__target__info__t" ],
    [ "_tdx_report_data_t", "struct__tdx__report__data__t.html", "struct__tdx__report__data__t" ],
    [ "_tdx_uuid_t", "struct__tdx__uuid__t.html", "struct__tdx__uuid__t" ],
    [ "appraisal_request", "structappraisal__request.html", "structappraisal__request" ],
    [ "collect_token_args", "structcollect__token__args.html", "structcollect__token__args" ],
    [ "evidence", "structevidence.html", "structevidence" ],
    [ "evidence_adapter", "structevidence__adapter.html", "structevidence__adapter" ],
    [ "get_nonce_args", "structget__nonce__args.html", "structget__nonce__args" ],
    [ "get_token_args", "structget__token__args.html", "structget__token__args" ],
    [ "jwk_set", "structjwk__set.html", "structjwk__set" ],
    [ "jwks", "structjwks.html", "structjwks" ],
    [ "mock_adapter_context", "structmock__adapter__context.html", "structmock__adapter__context" ],
    [ "MockServer", "class_mock_server.html", "class_mock_server" ],
    [ "nonce", "structnonce.html", "structnonce" ],
    [ "policies", "structpolicies.html", "structpolicies" ],
    [ "quote_request", "structquote__request.html", "structquote__request" ],
    [ "Request", "struct_request.html", "struct_request" ],
    [ "Response", "struct_response.html", "struct_response" ],
    [ "response_headers", "structresponse__headers.html", "structresponse__headers" ],
    [ "retry_config", "structretry__config.html", "structretry__config" ],
    [ "sgx_adapter_context", "structsgx__adapter__context.html", "structsgx__adapter__context" ],
    [ "tdx_adapter_context", "structtdx__adapter__context.html", "structtdx__adapter__context" ],
    [ "token", "structtoken.html", "structtoken" ],
    [ "trust_authority_connector", "structtrust__authority__connector.html", "structtrust__authority__connector" ],
    [ "write_headers", "structwrite__headers.html", "structwrite__headers" ],
    [ "write_result", "structwrite__result.html", "structwrite__result" ]
];